version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8081:8080"

  mysql-student:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
    ports:
      - "3306:3306"

  mysql-class:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: classedb
    ports:
      - "3307:3306"

  student-service:
    build: ./student-service
    ports:
      - "8081:8080"
    depends_on:
      - mysql-student

  class-service:
    build: ./class-service
    ports:
      - "8082:8080"
    depends_on:
      - mysql-class

  react-frontend:
    build: ./frontend
    ports:
      - "3000:3000"
